
"""
Problem Each new term in the Fibonacci Sequence is generated by adding the previous two terms. By starting with 1 and 2, the 
first 10 terms will be : 1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci Sequence until 4000000, find the sum of the even-valued terms.
"""

def fib():
    a,b = 1, 2 # initialized the first two number in the sequence
    sum = 0
    while b < 4000000: # while loop stops at when b is equal to 4 000 000
        if (b % 2) == 0: # check is n is a even number
            sum += b #adding even numbers to sum
        a,b = b, a+b # updating a to be b and b to be the next next number in the sequence.
    print("The sum of even fibonacci numbers until 4 million is " + str(sum))

fib()

'''
TODO: take in a integer N where N is the upper limit. So, it would me sum of even fibonacci numbers up to N.
'''
