
"""
Problem Each new term in the Fibonacci Sequence is generated by adding the previous two terms. By starting with 1 and 2, the 
first 10 terms will be : 1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci Sequence whose values do not exceed N, find the sum of the even-valued terms.
"""
# n = int(input("Enter value: "))
n = 100
def fib(n):
    x = 2
    a, b = 2, 8
    while b < n:
        x += b
        a, b = b, 4 * b + a
    print(x)

fib(n)

